# Generated by Django 5.2.4 on 2025-10-07 14:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('project', '0001_initial'), ('project', '0002_userproject_project_use_uuid_d642a6_idx'), ('project', '0003_projectdocument'), ('project', '0004_projectdocument_ai_error_message_and_more'), ('project', '0005_projectdocument_api_collection_and_more'), ('project', '0006_projectdocument_file_id'), ('project', '0007_projectdocument_original_filename'), ('project', '0008_projectdocument_doc_id'), ('project', '0009_functionalrequirement')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='project_use_user_id_68fecb_idx'), models.Index(fields=['project_name'], name='project_use_project_ff5509_idx'), models.Index(fields=['uuid'], name='project_use_uuid_d642a6_idx')],
                'unique_together': {('user', 'project_name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('link', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='project.userproject')),
                ('ai_error_message', models.TextField(blank=True, null=True)),
                ('ai_processed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('api_collection', models.CharField(blank=True, help_text='Collection name used in API', max_length=255, null=True)),
                ('api_response', models.JSONField(blank=True, help_text='Full API response data', null=True)),
                ('file_id', models.CharField(blank=True, help_text='File ID from upload API', max_length=255, null=True)),
                ('original_filename', models.CharField(blank=True, help_text='Original filename before upload', max_length=255, null=True)),
                ('doc_id', models.CharField(blank=True, help_text='Document ID from preprocessing API', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=500)),
                ('section_content', models.TextField()),
                ('section_type', models.CharField(choices=[('api_endpoint', 'API Endpoint'), ('function', 'Function'), ('class', 'Class'), ('method', 'Method'), ('parameter', 'Parameter'), ('response', 'Response'), ('example', 'Example'), ('other', 'Other')], default='other', max_length=50)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='project.projectdocument')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr_info_id', models.UUIDField(help_text='FR info ID from API', unique=True)),
                ('fr_group', models.CharField(help_text="FR group like 'u-fr-001: User Service'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='FR description')),
                ('is_selected', models.BooleanField(default=False, help_text='Whether FR is selected by user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_requirements', to='project.userproject')),
            ],
            options={
                'ordering': ['fr_group'],
                'unique_together': {('project', 'fr_info_id')},
            },
        ),
    ]
