# Generated by Django 5.2.4 on 2025-08-09 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userproject',
            index=models.Index(fields=['uuid'], name='project_use_uuid_d642a6_idx'),
        ),
    ]
