# Generated by Django 5.2.4 on 2025-09-04 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='ai_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='ai_processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=500)),
                ('section_content', models.TextField()),
                ('section_type', models.CharField(choices=[('api_endpoint', 'API Endpoint'), ('function', 'Function'), ('class', 'Class'), ('method', 'Method'), ('parameter', 'Parameter'), ('response', 'Response'), ('example', 'Example'), ('other', 'Other')], default='other', max_length=50)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='project.projectdocument')),
            ],
        ),
    ]
