# Generated by Django 4.2.7 on 2024-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectdocument_ai_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='api_collection',
            field=models.CharField(blank=True, help_text='Collection name used in API', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='api_response',
            field=models.JSONField(blank=True, help_text='Full API response data', null=True),
        ),
    ]
