# Generated by Django 5.2.4 on 2025-09-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_projectdocument_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename before upload', max_length=255, null=True),
        ),
    ]

