# Generated by Django 5.2.4 on 2025-10-05 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_projectdocument_doc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr_info_id', models.UUIDField(help_text='FR info ID from API', unique=True)),
                ('fr_group', models.CharField(help_text="FR group like 'u-fr-001: User Service'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='FR description')),
                ('is_selected', models.BooleanField(default=False, help_text='Whether FR is selected by user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_requirements', to='project.userproject')),
            ],
            options={
                'ordering': ['fr_group'],
                'unique_together': {('project', 'fr_info_id')},
            },
        ),
    ]
