# Generated by Django 5.2.4 on 2025-11-26 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial_squashed_0009_functionalrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('api_name', models.CharField(help_text="API endpoint name like 'Create Project', 'Delete Project'", max_length=255)),
                ('http_method', models.CharField(default='POST', help_text='HTTP method: GET, POST, PUT, DELETE, etc.', max_length=10)),
                ('request_url', models.CharField(blank=True, help_text='Full request URL', max_length=500, null=True)),
                ('request_headers', models.JSONField(blank=True, default=dict, help_text='Request headers as JSON object')),
                ('test_case_id', models.IntegerField(help_text='Test case ID from API')),
                ('test_case_name', models.CharField(help_text='Test case description', max_length=500)),
                ('test_category', models.CharField(choices=[('basic_validation', 'Basic Validation'), ('business_logic', 'Business Logic')], default='basic_validation', max_length=50)),
                ('request_body_template', models.JSONField(blank=True, default=dict, help_text='Original request body template')),
                ('request_mapping', models.JSONField(blank=True, default=dict, help_text='Request mapping with specific values')),
                ('expected_output', models.JSONField(blank=True, default=dict, help_text='Expected response output')),
                ('test_case_data', models.JSONField(blank=True, default=dict, help_text='Complete test case data as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_test_cases', to='project.userproject')),
            ],
            options={
                'ordering': ['api_name', 'test_category', 'test_case_id'],
                'indexes': [models.Index(fields=['project'], name='project_gen_project_f19f4f_idx'), models.Index(fields=['api_name'], name='project_gen_api_nam_310176_idx'), models.Index(fields=['test_category'], name='project_gen_test_ca_431b99_idx'), models.Index(fields=['uuid'], name='project_gen_uuid_47f8e9_idx'), models.Index(fields=['created_at'], name='project_gen_created_ebe159_idx')],
            },
        ),
    ]
