# Generated by Django 5.2.4 on 2025-08-08 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_suite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_suite.projecttestsuite')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['test_suite'], name='testcase_hi_test_su_b7de14_idx')],
            },
        ),
    ]
