# Generated by Django 5.2.4 on 2025-08-09 11:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_suite', '0002_projecttestsuite_uuid_and_more'),
        ('testcase_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasehistory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddIndex(
            model_name='testcasehistory',
            index=models.Index(fields=['uuid'], name='testcase_hi_uuid_d92577_idx'),
        ),
    ]
