# Generated by Django 5.2.4 on 2025-08-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcase_history', '0002_testcasehistory_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasehistory',
            name='test_case_name',
            field=models.CharField(default='Unnamed Test Case', max_length=255),
        ),
    ]
