# Generated by Django 5.2.4 on 2025-12-02 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_testsuitereport'),
        ('project', '0012_generatedtestcase_execute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('activity_type', models.CharField(choices=[('project_created', 'Project Created'), ('document_uploaded', 'Document Uploaded'), ('test_suite_executed', 'Test Suite Executed'), ('test_cases_generated', 'Test Cases Generated')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='testsuitereport',
            new_name='main_testsu_project_0a8ede_idx',
            old_name='main_testsui_project_idx',
        ),
        migrations.RenameIndex(
            model_name='testsuitereport',
            new_name='main_testsu_test_su_4b4600_idx',
            old_name='main_testsui_test_su_idx',
        ),
        migrations.RenameIndex(
            model_name='testsuitereport',
            new_name='main_testsu_test_su_e8b737_idx',
            old_name='main_testsui_test_su_rep_idx',
        ),
        migrations.RenameIndex(
            model_name='testsuitereport',
            new_name='main_testsu_status_41f2a3_idx',
            old_name='main_testsui_status_idx',
        ),
        migrations.RenameIndex(
            model_name='testsuitereport',
            new_name='main_testsu_uuid_b32c09_idx',
            old_name='main_testsui_uuid_idx',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='project.userproject'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user'], name='main_userac_user_id_d4b0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['activity_type'], name='main_userac_activit_8aff9e_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['created_at'], name='main_userac_created_2e9351_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['project'], name='main_userac_project_60edbb_idx'),
        ),
    ]
