# Generated by Django 5.2.4 on 2025-08-08 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_suite_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.userproject')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project'], name='test_suite__project_3768f4_idx'), models.Index(fields=['test_suite_name'], name='test_suite__test_su_cfc77f_idx')],
                'unique_together': {('project', 'test_suite_name')},
            },
        ),
    ]
