# Generated by Django 5.2.4 on 2025-08-09 11:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_userproject_project_use_uuid_d642a6_idx'),
        ('test_suite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttestsuite',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddIndex(
            model_name='projecttestsuite',
            index=models.Index(fields=['uuid'], name='test_suite__uuid_8a8a70_idx'),
        ),
    ]
