# Generated by Django 5.2.4 on 2025-11-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_suite', '0002_projecttestsuite_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttestsuite',
            name='api_test_suite_id',
            field=models.CharField(blank=True, help_text='Test Suite ID from API', max_length=255, null=True),
        ),
    ]
